import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/app/components/ui/sonner";
import RouteGuard from "./components/route-guard";
import { AuthProvider } from "./contexts/auth-context";
import ClientLayout from "./components/client-layout";
import { DataProvider } from "./contexts/data-context";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Toaster />
        <AuthProvider>
          <DataProvider>
            <RouteGuard />
            <ClientLayout>{children}</ClientLayout>
          </DataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
